### ISSUE TITLE
Versionamento struttura documentazione

### ISSUE THREAD

**Issue by primes2h** [odoo-italia/documentazione#12]
Stavo pensando a una modifica sostanziale della struttura della documentazione.
Ci sono alcuni materiali della documentazione che sono indipendenti dalla versione (es. documentazione dei vari gruppi).
Altri invece sono specifici della versione, potrebbero essere le guide o i readme tradotti dei moduli dei repository OCA.

Questa la proposta:
1) Lasciare in master tutto ciò che non dipende dalla versione (es. sezione "Gruppi" o guide generiche)
2) Creare un branch per versione e gestire all'interno la documentazione specifica (es. moduli OCA e guide specifiche)

Il tema Odoo per la documentazione è già predisposto per il versionamento, basta impostare 
`canonical_root` e `versions` nel file `conf.py` come indicato nel file stesso:

![immagine](https://user-images.githubusercontent.com/227940/59962338-53268b00-94e4-11e9-80da-ea095a1c2cd1.png)

Cosa ne pensate?

**Comment by eLBati** [comment]
:+1:

**Comment by primes2h** [comment]
>     1. Lasciare in master tutto ciò che non dipende dalla versione (es. sezione "Gruppi" o guide generiche)
> 
>     2. Creare un branch per versione e gestire all'interno la documentazione specifica (es. moduli OCA e guide specifiche)
> 

Giusto per spiegare meglio come intenderei procedere.
I vari branch (10.0, 11.0, 12.0) vengono creati da master.

Se la documentazione da aggiungere è indipendente dalla versione (es. per i gruppi) la PR andrà fatta su master.
Se la documentazione è specifica per versione (es. traduzione readme moduli OCA) la PR andrà fatta sul branch della versione.

Una volta rigenerata la documentazione basterà copiare sul sito solo lo specifico branch modificato sotto

`/documentazione/<n._versione>/`

Se la modifica viene fatta su documentazione comune (quindi su master), basterà fare il rebase dei vari branch 10.0/11.0/12.0 relativamente a master e copiare ciascun branch sul sito (e non più master).

**Comment by eLBati** [comment]
Ma poi sul sito come pubblichiamo? Allo stesso modo di https://www.odoo.com/documentation/user ?

**Comment by primes2h** [comment]
> Ma poi sul sito come pubblichiamo? Allo stesso modo di https://www.odoo.com/documentation/user ?

Si, con le varie sottodir per le versioni.

Ad es.
https://www.odoo-italia.org/documentazione/10.0/
https://www.odoo-italia.org/documentazione/11.0/
https://www.odoo-italia.org/documentazione/12.0/

**Comment by eLBati** [comment]
Ok, quindi il repo potrebbe avere la stessa struttura di https://github.com/odoo/documentation-user

Vogliamo aggiungere master?

Altrimenti la regola

> Se la documentazione da aggiungere è indipendente dalla versione (es. per i gruppi) la PR andrà fatta su master

potrebbe diventare

> Se la documentazione da aggiungere è indipendente dalla versione (es. per i gruppi) la PR andrà fatta su tutti i branch

Anche perchè

> fare il rebase dei vari branch 10.0/11.0/12.0

non la vedo una buona pratica: riscrivere la storia di branch pubblicati come "ufficiali" è un po' come incrociare i flussi

**Comment by primes2h** [comment]
> Ok, quindi il repo potrebbe avere la stessa struttura di https://github.com/odoo/documentation-user
> 
> Vogliamo aggiungere master?

Preferei che il master non comparisse nella documentazione, ha poco senso e può creare confusione.

Anche documentation-user che hai indicato tu non lo usa:

![immagine](https://user-images.githubusercontent.com/227940/60034942-fc6bad80-96ab-11e9-9c73-3ae6f9bbfbb7.png)


> Altrimenti la regola
> 
> > Se la documentazione da aggiungere è indipendente dalla versione (es. per i gruppi) la PR andrà fatta su master
> 
> potrebbe diventare
> 
> > Se la documentazione da aggiungere è indipendente dalla versione (es. per i gruppi) la PR andrà fatta su tutti i branch

Che penso sia quello che fanno in documentation-user, se noti l'ultima sezione

![immagine](https://user-images.githubusercontent.com/227940/60035100-59676380-96ac-11e9-93db-ea5a2885d8c5.png)

è indipendente dalla versione (e il repo documentation-user non ha master)


> Anche perchè
> 
> > fare il rebase dei vari branch 10.0/11.0/12.0
> 
> non la vedo una buona pratica: riscrivere la storia di branch pubblicati come "ufficiali" è un po' come incrociare i flussi

In generale sono d'accordo con te, da notare però che in questo caso specifico le directory relative a sezioni indipendenti sono ben definite, così come quelle relative a sezioni "versionate", non ci sarebbe rischio di incrocio dei flussi. 
Una nota nel README su quali sono le dir potrebbe essere sufficiente.

**Comment by eLBati** [comment]
Se non usiamo master e seguiamo la struttura di documentation-user per me è meglio.

> in questo caso specifico le directory relative a sezioni indipendenti sono ben definite, così come quelle relative a sezioni "versionate",

Il problema principale di riscrivere la storia su branch uffciali è che poi i vari repo locali in giro per il mondo, dopo un rabase, avranno branches diverged. Creando quindi dubbi su come procedere o problemi di deploy

**Comment by primes2h** [comment]
> Se non usiamo master e seguiamo la struttura di documentation-user per me è meglio.

Tra le due soluzioni penso anch'io sia quella migliore.

Quindi, ricapitolando, per i documenti comuni andrà fatta una PR per ciascun branch, corretto?


> > in questo caso specifico le directory relative a sezioni indipendenti sono ben definite, così come quelle relative a sezioni "versionate",
> 
> Il problema principale di riscrivere la storia su branch uffciali è che poi i vari repo locali in giro per il mondo, dopo un rabase, avranno branches diverged. Creando quindi dubbi su come procedere o problemi di deploy

:+1:

**Comment by primes2h** [comment]
Up! :smile_cat: :pray:

**Comment by gregoril** [comment]
up!

**Comment by marcelofrare** [comment]
non entro nel merito degli aspetti tecnici di come ottenere il risultato, visto che non possiedo le conoscenze appropriate.
Posso invece dire che lo scenario ideale per me (se fosse possibile realizzarlo) é che per ogni versione ci sia tutta la documentazione pertinente, evitando di ricerche inutili.
Ovviamente la documentazione condivisa tra le diverse versioni, dovrà essere linkata da ogni versione verso lo stesso file

**Comment by eLBati** [comment]
Allora penso che possiamo procedere come hai ipotizzato @primes2h

**Comment by scigghia** [comment]
Concordo

**Comment by mymage** [comment]
Se e dico SE ho capito, la soluzione è di "copiare/aggiornare" la documentazione indipendente dalla versione in ogni branch di versione. Questo ha sicuramente il lato positivo di avere tutta la documentazione in una cartella, e non credo che la documentazione di base cambi molto spesso.
Forse dico una castronata, ma creare un branch "common" o "base" di riferimento solo per questa avrebbe senso (per liberare master)?

**Comment by primes2h** [comment]
> Se e dico SE ho capito, la soluzione è di "copiare/aggiornare" la documentazione indipendente dalla versione in ogni branch di versione. Questo ha sicuramente il lato positivo di avere tutta la documentazione in una cartella, e non credo che la documentazione di base cambi molto spesso.

Esatto. Una volta creata, è documentazione abbastanza statica.

> Forse dico una castronata, ma creare un branch "common" o "base" di riferimento solo per questa avrebbe senso (per liberare master)?

Avresti lo stesso problema di master, cambierebbe solo il nome del branch rispetto al quale fare il rebase.

**Comment by primes2h** [comment]
Ok, ho creato i tre branch, impostato la versione in conf.py e aggiunto qualche altra piccola correzione.
Spero sia tutto ok.

https://github.com/odoo-italia/documentazione

Procedo con l'impostare il branch principale (alla 12.0?) ed eliminare master?

**Comment by tafaRU** [comment]
> Procedo con l'impostare il branch principale (alla 12.0?) ed eliminare master?

:+1:

**Comment by eLBati** [comment]
@primes2h poi per la build su https://www.odoo-italia.org/documentazione/ bisogna fare qualcosa di particolare? Hai verificato anche il version switcher che indicavi nel commento https://github.com/odoo-italia/documentazione/issues/12#issuecomment-505081432 ?

**Comment by primes2h** [comment]
> @primes2h poi per la build su https://www.odoo-italia.org/documentazione/ bisogna fare qualcosa di particolare? Hai verificato anche il version switcher che indicavi nel commento [#12 (comment)](https://github.com/odoo-italia/documentazione/issues/12#issuecomment-505081432) ?

In teoria dovrebbe già essere a posto, per ciascun branch ho definito la relativa versione, ho impostato `canonical_root` a `/` e attivato i link a 10.0, 11.0 e 12.0. 

Dovrebbe essere sufficiente fare i build e mettere ciascuno sotto 
`...documentazione/<n_versione>/`

Penso sia anche da impostare il reindirizzamento da `.../documentazione/`

**Comment by primes2h** [comment]
@eLBati se 

> > @primes2h poi per la build su https://www.odoo-italia.org/documentazione/ bisogna fare qualcosa di particolare? Hai verificato anche il version switcher che indicavi nel commento [#12 (comment)](https://github.com/odoo-italia/documentazione/issues/12#issuecomment-505081432) ?
> 
> In teoria dovrebbe già essere a posto, per ciascun branch ho definito la relativa versione, ho impostato `canonical_root` a `/` e attivato i link a 10.0, 11.0 e 12.0.
> 
> Dovrebbe essere sufficiente fare i build e mettere ciascuno sotto
> `...documentazione/<n_versione>/`
> 
> Penso sia anche da impostare il reindirizzamento da `.../documentazione/`

@eLBati hai per caso provato?
Se è tutto ok, potrei chiudere la issue.

**Comment by eLBati** [comment]
> hai per caso provato?

In locale non ho provato. Però se hai provato tu per me OK

> Dovrebbe essere sufficiente fare i build e mettere ciascuno sotto
...documentazione/<n_versione>/

Lo faccio direttamente sul server?

Attualmente su `/var/www/documentazione` c'è il branch master. Quindi metto i vari branch in `/var/www/documentazione/<n_versione>/`?
Per https://www.odoo-italia.org/documentazione/ dovrò impostare il redirect a https://www.odoo-italia.org/documentazione/12.0 ?

**Comment by primes2h** [comment]
> > hai per caso provato?
> 
> In locale non ho provato. Però se hai provato tu per me OK
> 
> > Dovrebbe essere sufficiente fare i build e mettere ciascuno sotto
> > ...documentazione/<n_versione>/
> 
> Lo faccio direttamente sul server?
> 
> Attualmente su `/var/www/documentazione` c'è il branch master. Quindi metto i vari branch in `/var/www/documentazione/<n_versione>/`?

Direi di si.

> Per https://www.odoo-italia.org/documentazione/ dovrò impostare il redirect a https://www.odoo-italia.org/documentazione/12.0 ?

In pratica dovresti fare in modo che la pagina predefinita (quando selezioni la documentazione dal sito) passi da
`https://www.odoo-italia.org/documentazione/`
a
`https://www.odoo-italia.org/documentazione/12.0/`

Per quanto riguarda le altre versioni, nelle prove in locale se faccio clic su (ad es.) 11.0 attualmente punta a un path relativo `/11.0/`

**Comment by eLBati** [comment]
@primes2h su https://www.odoo-italia.org/documentazione/12.0/ trovi un primo risultato: il version switcher però non tiene conto del path `documentazione`. Sai mica come sistemarlo?
Grazie

**Comment by primes2h** [comment]
> @primes2h su https://www.odoo-italia.org/documentazione/12.0/ trovi un primo risultato: il version switcher però non tiene conto del path `documentazione`. Sai mica come sistemarlo?

Questo dovrebbe risolvere https://github.com/odoo-italia/documentazione/commit/e995ad142805152823f78e275ecd0578dbec4b2a

Se è tutto ok, faccio cherry pick per tutte le versioni.

**Comment by eLBati** [comment]
:+1:  https://www.odoo-italia.org/documentazione/12.0/

**Comment by primes2h** [comment]
Ok, ho aggiornato anche i branch 10.0 e 11.0.

Puoi caricarli.

P.S.: ho notato questa strana cosa.

In locale ottengo correttamente questo:
 
![image](https://user-images.githubusercontent.com/227940/65946410-5f50ab80-e436-11e9-9047-480802c5b17e.png)

Sul sito invece i titoli diventano link:

![image](https://user-images.githubusercontent.com/227940/65946466-7bece380-e436-11e9-8415-97fbb061ae7c.png)

Idee su come risolvere?

**Comment by eLBati** [comment]
Attualmente https://www.odoo-italia.org/documentazione/12.0 è uguale a https://www.odoo-italia.org/documentazione , perchè non sono riuscito a fare redirect di https://www.odoo-italia.org/documentazione e tutti i suoi subpath a https://www.odoo-italia.org/documentazione/12.0
Sai mica come farlo in nginx?

> Idee su come risolvere?

Magari dipende dalla build. Il virtualenv con cui la produco è
```
aadict (0.2.3)
alabaster (0.7.12)
asset (0.6.12)
Babel (2.7.0)
certifi (2019.3.9)
chardet (3.0.4)
docutils (0.14)
globre (0.1.5)
idna (2.8)
imagesize (1.1.0)
Jinja2 (2.10.1)
MarkupSafe (1.1.1)
packaging (19.0)
pip (9.0.1)
pkg-resources (0.0.0)
Pygments (2.4.2)
pyparsing (2.4.0)
pytz (2019.1)
requests (2.22.0)
setuptools (39.0.1)
six (1.12.0)
snowballstemmer (1.2.1)
Sphinx (1.8.5)
sphinx-patchqueue (1.0.4)
sphinxcontrib-websupport (1.1.2)
unidiff (0.5.5)
urllib3 (1.25.3)
Werkzeug (0.15.4)
```

**Comment by primes2h** [comment]
> Attualmente https://www.odoo-italia.org/documentazione/12.0 è uguale a https://www.odoo-italia.org/documentazione,

Per caso hai ancora master in `/var/www/documentazione` ?

 
> > Idee su come risolvere?
> 
> Magari dipende dalla build. Il virtualenv con cui la produco è
> 
> ```
> Sphinx (1.8.5)

Io uso 1.4.6.
Il problema si presenta per le versioni > 1.5.6
Come workaround temporaneo potresti usare la v 1.5.6 e rifare la build.

**Comment by eLBati** [comment]
> Per caso hai ancora master in /var/www/documentazione ?

Sì, ma `/documentazione` punta a `/var/www/documentazione/12.0/_build/html`

> Come workaround temporaneo potresti usare la v 1.5.6 e rifare la build

Fatto

**Comment by primes2h** [comment]
> > Per caso hai ancora master in /var/www/documentazione ?

master non ha più senso e andrebbe eliminato.

> Sì, ma `/documentazione` punta a `/var/www/documentazione/12.0/_build/html`

In realtà non funziona perché

`https://www.odoo-italia.org/documentazione/`

punta a master, infatti con un clic arrivo a

`https://www.odoo-italia.org/documentazione/traduzioni.html`

Che è la versione vecchia (che era in master)
 

> Sai mica come farlo in nginx?


https://www.liquidweb.com/kb/redirecting-urls-using-nginx/

**Comment by eLBati** [comment]
> Che è la versione vecchia (che era in master)

ctrl + F5 ?

> https://www.liquidweb.com/kb/redirecting-urls-using-nginx/

Sì, ma il problema sono i subpath.
Ad esempio fare redirect di
https://www.odoo-italia.org/documentazione/traduzioni/linee_guida/introduzione.html
a
https://www.odoo-italia.org/documentazione/12.0/traduzioni/linee_guida/introduzione.html

**Comment by primes2h** [comment]
> > Che è la versione vecchia (che era in master)
> 
> ctrl + F5 ?

:sweat_smile: 

> Sì, ma il problema sono i subpath.
> Ad esempio fare redirect di
> https://www.odoo-italia.org/documentazione/traduzioni/linee_guida/introduzione.html
> a
> https://www.odoo-italia.org/documentazione/12.0/traduzioni/linee_guida/introduzione.html

In teoria se fai il redirect da
https://www.odoo-italia.org/documentazione
a
https://www.odoo-italia.org/documentazione/12/

i subpath poi dovrebbero essere relativi, non assoluti.

Ad ogni modo nella situazione attuale anche se nell'url non compare 12.0 è indicato in alto a dx nel menù a discesa. Non è la soluzione ottimale ma almeno non rompe le pagine.

**Comment by eLBati** [comment]
> In teoria se fai il redirect da
https://www.odoo-italia.org/documentazione
a
https://www.odoo-italia.org/documentazione/12/

Intendo dire che con questo semplice redirect, se uno nel browser inserisse
https://www.odoo-italia.org/documentazione/traduzioni/linee_guida/introduzione.html
(perchè magari arriva da qualche link lasciato in giro) non verrebbe reindirizzato su https://www.odoo-italia.org/documentazione/12.0/traduzioni/linee_guida/introduzione.html

**Comment by primes2h** [comment]
> > In teoria se fai il redirect da
> > https://www.odoo-italia.org/documentazione
> > a
> > https://www.odoo-italia.org/documentazione/12/
> 
> Intendo dire che con questo semplice redirect, se uno nel browser inserisse
> https://www.odoo-italia.org/documentazione/traduzioni/linee_guida/introduzione.html
> (perchè magari arriva da qualche link lasciato in giro) non verrebbe reindirizzato su https://www.odoo-italia.org/documentazione/12.0/traduzioni/linee_guida/introduzione.html

Hai provato con `alias` ?

http://nginx.org/en/docs/http/ngx_http_core_module.html#alias

**Comment by eLBati** [comment]
Sì, è come è configurato adesso:
```
    location /documentazione {
       alias /var/www/documentazione/12.0/_build/html;
       index index.html;
    }
    location /documentazione/12.0 {
       alias /var/www/documentazione/12.0/_build/html;
       index index.html;
    }
    location /documentazione/11.0 {
       alias /var/www/documentazione/11.0/_build/html;
       index index.html;
    }
    location /documentazione/10.0 {
       alias /var/www/documentazione/10.0/_build/html;
       index index.html;
    }
```

**Comment by primes2h** [comment]
> Sì, è come è configurato adesso:
> 
> ```
>     location /documentazione {
>        alias /var/www/documentazione/12.0/_build/html;
>        index index.html;
>     }

Prova per curiosità a cambiare questo sopra così (con / alla fine):

<pre>
     location /documentazione/ {
        alias /var/www/documentazione/12.0/;
     }
</pre>

e lasciare il resto invariato.

**Comment by eLBati** [comment]
`403 Forbidden`

**Comment by primes2h** [comment]
@eLBati 

Questo dovrebbe fare al caso nostro:
https://stackoverflow.com/questions/18305189/nginx-rewrite-redirect-for-a-folder

**Comment by eLBati** [comment]
Quasi: `^/documentazione/(.*)` fa il match anche di `/documentazione/12.0` quindi fa redirect infinito a
`https://www.odoo-italia.org/documentazione/12.0/12.0/12.0/12.0/12.0/12.0/12.0/12.0/12.0/12.0/12.0/12.0/12.0/12.0 ...`

Se uso invece `^/documentazione/(?!.*(10\.0|11\.0|12\.0))` non riesco a usare il capturing group e `$1` è sempre vuoto

**Comment by primes2h** [comment]
Mmhh...

> Quasi: `^/documentazione/(.*)` fa il match anche di `/documentazione/12.0` quindi fa redirect infinito a

Mmmh....

Prova

`^/documentazione/([^/]*)$`

**Comment by eLBati** [comment]
Ok, dovrei aver fatto con
`^\/documentazione\/((?!12\.0|11\.0|10\.0).*)$`

@primes2h magari fai 2 test e poi chiudi pure.

Grazie

**Comment by primes2h** [comment]
Direi perfetto. :ok_hand: 

Grazie!
