### ISSUE TITLE
build documentazione con sphinx: esplicitare dipendenze

### ISSUE THREAD

**Issue by tafaRU** [odoo-italia/documentazione#7]
In locale sono riuscito a generare la build avendo nel mio virtualenv:

```
pip freeze
alabaster==0.7.12
Babel==2.6.0
certifi==2019.3.9
chardet==3.0.4
Click==7.0
docutils==0.14
idna==2.8
imagesize==1.1.0
Jinja2==2.10.1
MarkupSafe==1.1.1
packaging==19.0
pkg-resources==0.0.0
Pygments==2.4.0
pyparsing==2.4.0
pytz==2019.1
requests==2.21.0
six==1.12.0
snowballstemmer==1.2.1
Sphinx==1.8.5
sphinx-intl==1.0.0
sphinx-patchqueue==1.0.4
sphinxcontrib-websupport==1.1.0
unidiff==0.5.5
urllib3==1.24.3
Werkzeug==0.15.4

python3 -V
Python 3.6.7
```

Tra le dipendenze che ho dovuto installare segnalo:

* werkzeug
* sphinx-intl
* sphinx-patchqueue

Può aver senso aggiungerle al file `README`?

**Comment by tafaRU** [comment]
Si veda anche https://www.odoo.com/groups/community-59/community-13776438 come ulteriore riferimento.

**Comment by primes2h** [comment]
> 
> Tra le dipendenze che ho dovuto installare segnalo:
> 
>     * werkzeug
> 
>     * sphinx-intl
> 
>     * sphinx-patchqueue
> 
> 
> Può aver senso aggiungerle al file `README`?

Non sarebbe forse meglio un file requirements e indicare quello nel README?

**Comment by tafaRU** [comment]
> Non sarebbe forse meglio un file requirements e indicare quello nel README?

sì penso sia meglio.

**Comment by eLBati** [comment]
:+1:

**Comment by primes2h** [comment]
@tafaRU @eLBati 

Ho aperto questa PR #25
